all: count-mismatch-test type-mismatch-test

.PHONY: count-mismatch-test type-mismatch-test clean

count-mismatch-test:
	python3 count-mismatch-detection-test.py

type-mismatch-test:
	python3 type-mismatch-detection-test.py

clean:
	rm -rf *.txt

